### ISSUE TITLE
M6 without setting next tool via T fails.

### ISSUE THREAD

**Issue by MrLBeale** [Zealandia-Systems/Swordfish#46]
A reflash of 2.1 Dirty fixed the machine moving to caddy limit, instead of shifting to the soft limit when homing, probing or tool changing.
However,  after a power cycle the issue presents itself again and reflashing firmware fixes it.

**Comment by smohekey** [comment]
Does power cycling the controller also fix it?

**Comment by MrLBeale** [comment]
power cycling the controller caused the issue

**Comment by smohekey** [comment]
What is actually happening here is that each time a tool change occurs, the firmware sets the next tool to -1, expecting that a T code will be executed before the next M6 code. This results in the tool change stopping half way through, after it's stored the current tool as it has no next tool to select.
Instead, it should warn that the requested tool is already selected. Do this by never setting the next tool to -1.
